// Generated by model/write_shader_constants.py. Do not edit by hand.
// Offsets come from vgnn.weight_offsets(), which shares its ordering with
// Weights.arrays_in_file_order(), so the shaders cannot drift from the file
// layout the exporter writes.
#ifndef VGNN_WEIGHTS_HLSLI
#define VGNN_WEIGHTS_HLSLI

static const uint VGNN_INPUT_DIM = 10;
static const uint VGNN_HIDDEN_DIM = 16;
static const uint VGNN_OUTPUT_DIM = 3;
static const uint VGNN_PAYLOAD_FLOAT_COUNT = 448;

static const uint VGNN_INPUT_SCALE_OFFSET = 0;
static const uint VGNN_OUTPUT_SCALE_OFFSET = 10;
static const uint VGNN_SELF0_OFFSET = 13;
static const uint VGNN_NEIGHBOR0_OFFSET = 173;
static const uint VGNN_BIAS0_OFFSET = 333;
static const uint VGNN_SELF1_OFFSET = 349;
static const uint VGNN_NEIGHBOR1_OFFSET = 397;
static const uint VGNN_BIAS1_OFFSET = 445;

#endif // VGNN_WEIGHTS_HLSLI
