"""Generate the HLSL header holding VGNN dimensions and weight-buffer offsets.

The shaders previously hard-coded offsets such as ``SELF1_OFFSET = 349`` with no
mechanical link to the Python writer.  Reordering the payload would have produced
shaders that silently read the wrong floats: the CRC32 covers the bytes, not
their meaning, and only the golden case would have caught it, and only in verify
mode.  Generating the header from :func:`vgnn.weight_offsets` removes that class
of drift.

Only depends on NumPy, so CI can regenerate and diff without PyTorch.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from vgnn import HIDDEN_DIM, INPUT_DIM, OUTPUT_DIM, weight_offsets

DEFAULT_OUTPUT = (
    Path(__file__).parents[1] / "overlay" / "shaders" / "hlsl" / "gnncloth" / "vgnn_weights.hlsli"
)


def render() -> str:
    offsets = weight_offsets()
    lines = [
        "// Generated by model/write_shader_constants.py. Do not edit by hand.",
        "// Offsets come from vgnn.weight_offsets(), which shares its ordering with",
        "// Weights.arrays_in_file_order(), so the shaders cannot drift from the file",
        "// layout the exporter writes.",
        "#ifndef VGNN_WEIGHTS_HLSLI",
        "#define VGNN_WEIGHTS_HLSLI",
        "",
        f"static const uint VGNN_INPUT_DIM = {INPUT_DIM};",
        f"static const uint VGNN_HIDDEN_DIM = {HIDDEN_DIM};",
        f"static const uint VGNN_OUTPUT_DIM = {OUTPUT_DIM};",
        f"static const uint VGNN_PAYLOAD_FLOAT_COUNT = {offsets['PAYLOAD_FLOAT_COUNT']};",
        "",
    ]
    for name in ("INPUT_SCALE", "OUTPUT_SCALE", "SELF0", "NEIGHBOR0", "BIAS0", "SELF1", "NEIGHBOR1", "BIAS1"):
        lines.append(f"static const uint VGNN_{name}_OFFSET = {offsets[name]};")
    lines += ["", "#endif // VGNN_WEIGHTS_HLSLI", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the file on disk differs from what would be generated",
    )
    args = parser.parse_args()

    content = render()
    if args.check:
        if not args.output.exists():
            raise SystemExit(f"{args.output} does not exist; run without --check to generate it")
        current = args.output.read_text(encoding="utf-8")
        if current != content:
            raise SystemExit(
                f"{args.output} is stale. Run model/write_shader_constants.py and rebuild the SPIR-V."
            )
        print(f"{args.output.name} is up to date")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
